import "../public/globals.css";
import { Inter } from "next/font/google";
import Providers from "../store/providers";
import Layout from "../components/Layout";
import LoadSpinner from "../components/LoadSpinner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Providers>
            <Layout>
              {children}
              <LoadSpinner />
            </Layout>
          </Providers>
        </main>
      </body>
    </html>
  );
}
